# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.17.x'
    displayName: 'Install Node.js'

  - script: npm install --legacy-peer-deps
    displayName: 'Install Dependencies'

  - script: npx ng build --configuration staging
    displayName: 'Build'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: './dist'
      ArtifactName: 'arpa-web-app-staging'
      publishLocation: 'Container'
    displayName: 'Publish Artifacts'
