name: Cypress Tests

on: push

jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend
        uses: actions/checkout@v4
        with:
            repository: orso-co/Orso.Arpa.Api
            path: backend
            ref: fix-docker-compose
      - name: Start backend
        run: |
          cd backend
          docker-compose up -d
          cd ..
          sudo rm -R backend
      - name: Checkout frontend
        uses: actions/checkout@v4
        with:
            repository: orso-co/Orso.Arpa.Web
            path: frontend
      - name: Install dependencies
        run: |
          cd frontend
          npm install --legacy-peer-deps
      - name: Run cypress tests on chromium
        run: cd frontend && (npm start &) && npx cypress run -b chromium
      - name: Run cypress tests on firefox
        run: |
          sudo snap install firefox
          cd frontend && npx cypress run -b firefox
      - name: Run cypress tests on chrome
        run: cd frontend && npx cypress run -b chrome
            
      