name: Cypress Tests

on: push

jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Build api-server
        uses: orso-co/Orso.Arpa.Api
        run: docker build -t api < Dockerile
      - name: Run cypress tests
        uses: cypress-io/github-action@v6
        with:
          install-command: npm install --legacy-peer-deps
          start: npm start
      