name: Cypress Tests

on: push

jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend
        uses: actions/checkout@v4
        with:
            repository: orso-co/Orso.Arpa.Api
            path: backend
      - name: Start backend
        run: |
          cd backend
          sudo docker-compose build
          sudo docker-compose up -d
          docker-compose stop api
          cd ..
          sudo rm -R backend
      - name: Checkout frontend
        uses: actions/checkout@v4
        with:
            repository: orso-co/Orso.Arpa.Web
            path: frontend
      - name: Install dependencies
        run: |
          cd frontend
          npm install --legacy-peer-deps
      - name: Run cypress tests
        run: cd frontend && (npm start &) && npx cypress run
            
      