name: Cypress Tests

on: push

jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend
        uses: actions/checkout@v4
          with:
            repository: orso-co/Orso.Arpa.Api
      - name: Build backend
        uses: isbang/compose-action@v1.5.1
            compose-file: "./docker-compose.yml"
      - name: Checkout frontend
        uses: actions/checkout@v4
      - name: Run cypress tests
        uses: cypress-io/github-action@v6
        with:
          install-command: npm install --legacy-peer-deps
          start: npm start
      